// Auto-generated by scripts/update-schema.ts — do not edit manually
// Generated at: 2026-02-08T12:10:30.528Z

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      daily_stats: {
        Row: {
          id: string
          store_id: string | null
          date: string
          revenue: number | null
          cost: number | null
          profit: number | null
          orders_count: number | null
        }
        Insert: {
          id?: string
          store_id?: string | null
          date: string
          revenue?: number | null
          cost?: number | null
          profit?: number | null
          orders_count?: number | null
        }
        Update: {
          id?: string
          store_id?: string | null
          date?: string
          revenue?: number | null
          cost?: number | null
          profit?: number | null
          orders_count?: number | null
        }
        Relationships: []
      }
      message_logs: {
        Row: {
          id: string
          store_id: string | null
          order_id: string | null
          phone: string
          message: string
          status: string | null
          sent_at: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          store_id?: string | null
          order_id?: string | null
          phone: string
          message: string
          status?: string | null
          sent_at?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          store_id?: string | null
          order_id?: string | null
          phone?: string
          message?: string
          status?: string | null
          sent_at?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      message_templates: {
        Row: {
          id: string
          store_id: string | null
          trigger_type: string
          name: string
          template_kz: string | null
          template_ru: string | null
          active: boolean | null
          created_at: string | null
        }
        Insert: {
          id?: string
          store_id?: string | null
          trigger_type: string
          name: string
          template_kz?: string | null
          template_ru?: string | null
          active?: boolean | null
          created_at?: string | null
        }
        Update: {
          id?: string
          store_id?: string | null
          trigger_type?: string
          name?: string
          template_kz?: string | null
          template_ru?: string | null
          active?: boolean | null
          created_at?: string | null
        }
        Relationships: []
      }
      operational_expenses: {
        Row: {
          id: string
          store_id: string | null
          name: string
          amount: number
          start_date: string
          end_date: string
          product_id: string | null
          product_group: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          store_id?: string | null
          name: string
          amount: number
          start_date: string
          end_date: string
          product_id?: string | null
          product_group?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          store_id?: string | null
          name?: string
          amount?: number
          start_date?: string
          end_date?: string
          product_id?: string | null
          product_group?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      restock_orders: {
        Row: {
          id: string
          store_id: string | null
          supplier: string
          status: string
          order_date: string | null
          expected_date: string | null
          items: Json | null
          total_amount: number
          delivery_cost: number
          notes: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          store_id?: string | null
          supplier: string
          status?: string
          order_date?: string | null
          expected_date?: string | null
          items?: Json | null
          total_amount?: number
          delivery_cost?: number
          notes?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          store_id?: string | null
          supplier?: string
          status?: string
          order_date?: string | null
          expected_date?: string | null
          items?: Json | null
          total_amount?: number
          delivery_cost?: number
          notes?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      orders: {
        Row: {
          id: string
          store_id: string | null
          kaspi_order_id: string
          customer_name: string | null
          customer_phone: string | null
          delivery_address: string | null
          delivery_date: string | null
          status: string | null
          total_amount: number
          items: Json | null
          created_at: string | null
          completed_at: string | null
          delivery_mode: string | null
          delivery_cost: number | null
        }
        Insert: {
          id?: string
          store_id?: string | null
          kaspi_order_id: string
          customer_name?: string | null
          customer_phone?: string | null
          delivery_address?: string | null
          delivery_date?: string | null
          status?: string | null
          total_amount: number
          items?: Json | null
          created_at?: string | null
          completed_at?: string | null
          delivery_mode?: string | null
          delivery_cost?: number | null
        }
        Update: {
          id?: string
          store_id?: string | null
          kaspi_order_id?: string
          customer_name?: string | null
          customer_phone?: string | null
          delivery_address?: string | null
          delivery_date?: string | null
          status?: string | null
          total_amount?: number
          items?: Json | null
          created_at?: string | null
          completed_at?: string | null
          delivery_mode?: string | null
          delivery_cost?: number | null
        }
        Relationships: []
      }
      pricelist_feeds: {
        Row: {
          id: string
          store_id: string
          feed_token: string
          auth_login: string | null
          auth_password: string | null
          preorder_overrides: Json | null
          cached_xml: string | null
          cached_at: string | null
          enabled: boolean | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          store_id: string
          feed_token?: string
          auth_login?: string | null
          auth_password?: string | null
          preorder_overrides?: Json | null
          cached_xml?: string | null
          cached_at?: string | null
          enabled?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          store_id?: string
          feed_token?: string
          auth_login?: string | null
          auth_password?: string | null
          preorder_overrides?: Json | null
          cached_xml?: string | null
          cached_at?: string | null
          enabled?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      products: {
        Row: {
          id: string
          store_id: string | null
          kaspi_id: string | null
          name: string
          sku: string | null
          price: number | null
          cost_price: number | null
          quantity: number | null
          kaspi_stock: number | null
          image_url: string | null
          category: string | null
          active: boolean | null
          product_group: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          store_id?: string | null
          kaspi_id?: string | null
          name: string
          sku?: string | null
          price?: number | null
          cost_price?: number | null
          quantity?: number | null
          kaspi_stock?: number | null
          image_url?: string | null
          category?: string | null
          active?: boolean | null
          product_group?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          store_id?: string | null
          kaspi_id?: string | null
          name?: string
          sku?: string | null
          price?: number | null
          cost_price?: number | null
          quantity?: number | null
          kaspi_stock?: number | null
          image_url?: string | null
          category?: string | null
          active?: boolean | null
          product_group?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      stores: {
        Row: {
          id: string
          user_id: string | null
          name: string
          kaspi_merchant_id: string | null
          whatsapp_connected: boolean | null
          whatsapp_phone: string | null
          created_at: string | null
          kaspi_api_key: string | null
          whatsapp_session: Json | null
          kaspi_session: Json | null
          marketing_session: Json | null
          commission_rate: number | null
          tax_rate: number | null
          last_synced_at: string | null
        }
        Insert: {
          id?: string
          user_id?: string | null
          name: string
          kaspi_merchant_id?: string | null
          whatsapp_connected?: boolean | null
          whatsapp_phone?: string | null
          created_at?: string | null
          kaspi_api_key?: string | null
          whatsapp_session?: Json | null
          kaspi_session?: Json | null
          marketing_session?: Json | null
          commission_rate?: number | null
          tax_rate?: number | null
          last_synced_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string | null
          name?: string
          kaspi_merchant_id?: string | null
          whatsapp_connected?: boolean | null
          whatsapp_phone?: string | null
          created_at?: string | null
          kaspi_api_key?: string | null
          whatsapp_session?: Json | null
          kaspi_session?: Json | null
          marketing_session?: Json | null
          commission_rate?: number | null
          tax_rate?: number | null
          last_synced_at?: string | null
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string | null
          plan: string | null
          status: string | null
          addons: string[] | null
          start_date: string | null
          end_date: string | null
          auto_renew: boolean | null
        }
        Insert: {
          id?: string
          user_id?: string | null
          plan?: string | null
          status?: string | null
          addons?: string[] | null
          start_date?: string | null
          end_date?: string | null
          auto_renew?: boolean | null
        }
        Update: {
          id?: string
          user_id?: string | null
          plan?: string | null
          status?: string | null
          addons?: string[] | null
          start_date?: string | null
          end_date?: string | null
          auto_renew?: boolean | null
        }
        Relationships: []
      }
      users: {
        Row: {
          id: string
          email: string
          name: string
          phone: string | null
          avatar_url: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          email: string
          name: string
          phone?: string | null
          avatar_url?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          email?: string
          name?: string
          phone?: string | null
          avatar_url?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
    }
  }
}
